# Generated by Django 4.1.13 on 2024-07-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0003_author_user_quote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
